
~/Informatique/S3/bin/CreerMatrice: CreerMatrice.c
	gcc -I ~/Informatique/S3/include/matrice.h -Wall -Werror -Wextra -DTESTS -ggdb3 CreerMatrice.c -o ~/Informatique/S3/bin/CreerMatrice

run/CreerMatrice.c: ~/Informatique/S3/bin/CreerMatrice
	~/Informatique/S3/bin/CreerMatrice

Creermatrice.o: CreerMatrice.c
	gcc -I ~:Informatique/S3/include -Wall -Werror -Wextra -ggdb3 -c CreerMatrice.c
